version: '2'
services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
  mongo:
    image: mongo
  railsvm:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - mongo
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_HOST=postgres
      - POSTGRES_PASSWORD=postgres
      - MONGO_HOST=mongo:27017